version: '2'

services:
  base:
    image: soundboard-base
    volumes:
      - .:/app/
    working_dir: /app/
  install:
    extends:
      service: base
    command: bash -c "npm install && bower install --allow-root"
  build:
    extends:
      service: base
    command: bash -c "gulp init && gulp build"
